server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    root: INFO
    com.pricepal.backend: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  profiles:
    active: dev
    config:
      activate:
        on-profile: default
      import: optional:classpath:.env

# CORS 설정
cors:
  allowed-origin-patterns: "*"
  allow-credentials: true
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
    key: AIzaSyDIyXd--Z62Mwr6qR6AFLvzEJW-tLfa3KQ
external:
  api:
    url: "http://apis.data.go.kr/1262000/CountryFlagService2/getCountryFlagList2"
    key: "WCwXdDTnj5Fm2%2BBNXl8blFfMTTD4bwVCqx6Rp6SzaAEiR4wUgmA0Oy%2F4Jc%2BFCqrZcQHcLNKgT0SOr2OmRV%2Bu7A%3D%3D"

unsplash:
  access-key: eBNrw3HlHta-vMFlXtEGJGmLeyOGJq_ypbJK-rsaaj0

exchange:
  api:
    url: https://v6.exchangerate-api.com/v6
    key: eba85da9b502ab8e669e6f7d

timezone:
  api:
    key: BP9CIRD43Q8I
    url: https://api.timezonedb.com
