server:
  port: 8080

logging:
  level:
    root: INFO
    com.pricepal.backend: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet

# CORS 설정
cors:
  allowed-origin-patterns: "*"
  allow-credentials: true
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

external:
